### model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
quantization_bit: 4
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 2
lora_target: all

### dataset
dataset: skin_flap_train_1_2  #, text_recongnition_zh_en
eval_dataset: skin_flap_test_0  # ← **add** this line
cutoff_len: 5392
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 4

### output
output_dir: saves/skin_flap_qwen3b/lora/epoch3 
logging_steps: 1
save_steps: 250
plot_loss: true
overwrite_output_dir: true
seed: 3407

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 0.00005
num_train_epochs: 5
lr_scheduler_type: linear
optim: adamw_torch
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
use_accelerate: true

### eval
# val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 250

cache_dir: cache

# ### ray
# ray_run_name: qwen2.5-vl
# ray_num_workers: 1  # number of GPUs to use
# resources_per_worker:
#   GPU: 1
# placement_strategy: PACK
