### model
model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct
adapter_name_or_path: saves/skin_flap_qwen3b/lora/epoch3/checkpoint-70
trust_remote_code: true

### method
finetuning_type: lora

# export
export_dir: saves/Qwen2.5-VL-7B-Instruct-Lora-SFT-Checkpoint11000
export_device: auto
